version: "3.1"
services:
    db:
      image: mariadb
      container_name: mymariadb
      working_dir: /application
      volumes:
       - .:/application
      environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=database
       - MYSQL_USER=user
       - MYSQL_PASSWORD=password

    adminer:
     depends_on:
      - db
     image: adminer
     container_name: myadminer
     working_dir: /application
     volumes:
       - .:/application
     ports:
      - 50000:80

    php-apache:
     depends_on:
      - db
     build:
      context: ./
      dockerfile: Dockerfile
     volumes:
      - .:/application 
     ports:
      - 30000:80
